language: generic

before_install:
  before_install:
  - wget https://releases.hashicorp.com/terraform/0.12.5/terraform_0.12.5_linux_amd64.zip
  - unzip terraform_0.12.5_linux_amd64.zip
#These two steps will effectively validate our terraform and output a list of any changes to be made to our infrastructure
script:
 - chmod 777 deploy.sh
 - ./deploy.sh "$Approve" 